### ISSUE TITLE
界面乱码

### ISSUE THREAD

**Issue by SOVLOOKUP** [yuedun/zhuque#1]
![image](https://user-images.githubusercontent.com/53158137/120103459-3e4bdb00-c182-11eb-9fb6-a356fd3763ba.png)

**Comment by yuedun** [comment]
数据库中是正常的吗？

**Comment by yuedun** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/53158137/120103459-3e4bdb00-c182-11eb-9fb6-a356fd3763ba.png)

数据库中是正常的吗？

**Comment by SOVLOOKUP** [comment]
> > ![image](https://user-images.githubusercontent.com/53158137/120103459-3e4bdb00-c182-11eb-9fb6-a356fd3763ba.png)
> 
> 数据库中是正常的吗？

是的 select出来是正常中文 用的mysql，utf8mb4

**Comment by yuedun** [comment]
> 
> 
> > > ![image](https://user-images.githubusercontent.com/53158137/120103459-3e4bdb00-c182-11eb-9fb6-a356fd3763ba.png)
> > 
> > 
> > 数据库中是正常的吗？
> 
> 是的 select出来是正常中文 用的mysql，utf8mb4

可以查看浏览器控制台接口返回是否乱码，其次排查您的数据库字符集编码

**Comment by SOVLOOKUP** [comment]
> > > > ![image](https://user-images.githubusercontent.com/53158137/120103459-3e4bdb00-c182-11eb-9fb6-a356fd3763ba.png)
> > > 
> > > 
> > > 数据库中是正常的吗？
> > 
> > 
> > 是的 select出来是正常中文 用的mysql，utf8mb4
> 
> 可以查看浏览器控制台接口返回是否乱码，其次排查您的数据库字符集编码

接口中是乱码：
![image](https://user-images.githubusercontent.com/53158137/120290033-81c65680-c2f4-11eb-9a7c-bc7348661ff1.png)

数据库中正常：
![image](https://user-images.githubusercontent.com/53158137/120290287-c81bb580-c2f4-11eb-800d-3c07f5b68868.png)


是不是GO的后端解析出了问题？

**Comment by yuedun** [comment]
@SOVLOOKUP go后端是查询直出的，并没有字符集设置。
请查看dbpath配置是否指定charset
```
dialects: mysql
dbpath: "root:root@/zhuque?charset=utf8&parseTime=True&loc=Local"
```
查看mysql字符集设置
` show variables like '%char%'; `

**Comment by SOVLOOKUP** [comment]
![image](https://user-images.githubusercontent.com/53158137/120312409-41be9e00-c30b-11eb-8b44-40607805de08.png)
![image](https://user-images.githubusercontent.com/53158137/120312382-3bc8bd00-c30b-11eb-9153-4642335c3e32.png)

**Comment by yuedun** [comment]
@SOVLOOKUP 您的client，connecton，results与我的有些不同，大多数中文乱码问题都是与不正确的编码有关
![360截图20210602101120689](https://user-images.githubusercontent.com/7362116/120413572-21362880-c38b-11eb-8f1d-976015d48b10.jpg)

**Comment by SOVLOOKUP** [comment]
字符集修改为 utf8mb4_general_ci 即可
